server:
  port: 10010

spring:
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002 #,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
      timeout: 1000 #连接超时（毫秒）
      threads: 16
      nettyThreads: 32
      lettuce:
        pool:
          max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5 # 连接池中的最小空闲连接