server:
  port: 12000
spring:
  application:
    name: docker-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=tarzan_common
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    pers.benj: ${LOG_LEVEL:info}