server:
  port: 11000
spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/properties/
  application:
    name: Service-First
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    pers.benj: ${LOG_LEVEL:debug}