server:
  port: 11000
spring:
  #  cloud:
  #    config:
  #      server:
  #        native:
  #          search-locations: classpath:/properties/
  application:
    name: Service-First
  zipkin:
    base-url: http://localhost:9411/
    # 若在同一个注册中心的话可以启用自动发现，省略base-url
    locator:
      discovery:
        enabled: true #自动发现
    sleuth:
      sampler:
        percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    pers.benj: ${LOG_LEVEL:debug}