server:
  port: 8010
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/
  application:
   name: Config-Center
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/