server:
  port: 11010
spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/properties/
  application:
    name: Service-Second
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/