server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: Gateway-Center
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  zipkin:
    base-url: http://localhost:9411/
    # 若在同一个注册中心的话可以启用自动发现，省略base-url
    locator:
      discovery:
        enabled: true #自动发现
    sleuth:
      sampler:
        percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/